import type { Metadata } from "next";
import Breadcrumbs from "@/components/Breadcrumbs ";
import PageHeader from "@/components/PageHeader";
import PageFooter from "@/components/PageFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SiteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <PageHeader />
      <Breadcrumbs />
      {children}
      <PageFooter />
    </>
  );
}
