import type { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Products Page",
  description: "Products Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <nav>
      <ul className="flex gap-2">
        <li ><Link href='/'>Home</Link></li>
        <li><Link href='/products'>Products</Link></li>
      </ul>
    </nav>
    {children}
    </>
  );
}
